<!DOCTYPE html>
<html>
<body style="font-family: Arial, sans-serif; line-height: 1.5; color: #1e293b; padding: 15px;">
    <h2 style="color: #0f172a; margin-bottom: 5px;">Daily Social & Media Risk Monitoring Report</h2>
    <p style="color: #64748b; font-size: 14px; margin-top: 0;">Date: <strong>{{ $reportDate }}</strong> | Upper Trishuli-1 Hydropower Project</p>

    <div style="background: #f8fafc; border-left: 4px solid #2563eb; padding: 12px 15px; margin: 15px 0;">
        <p style="margin: 0;"><strong>Status:</strong> Highest Risk Tier: <strong>{{ $highestRisk }}</strong></p>
        <p style="margin: 4px 0 0 0;"><strong>Total Items Monitored:</strong> {{ $totalMentions }}</p>
    </div>

    <p>Please find attached the official PDF report containing the Executive Assessment, Itemized Findings, and Quantitative Sentiment Breakdown.</p>

    <hr style="border: none; border-top: 1px solid #e2e8f0; margin: 20px 0;">
    <p style="font-size: 12px; color: #94a3b8;">This  daily report was generated by Tamakoshi Monitor (UT-1 Risk Intelligence System).</p>
</body>
</html>