<!DOCTYPE html>
<html>
<body style="font-family: Arial, sans-serif; line-height: 1.5; color: #1e293b; padding: 15px;">
    <h2 style="color: #0f172a; margin-bottom: 4px;">
        Social & Media Risk Monitoring Report — <span style="color: #2563eb;">{{ $slotTime }}</span>
    </h2>
    <p style="color: #64748b; font-size: 13px; margin-top: 0;">
        Date: <strong>{{ $reportDate }}</strong> | Upper Trishuli-1 Hydropower Project (216 MW)
    </p>

    <div style="background: #f8fafc; border-left: 4px solid #2563eb; padding: 12px 16px; margin: 15px 0; border-radius: 4px;">
        <p style="margin: 0; font-size: 14px;"><strong>Monitoring Cycle:</strong> {{ $slotTime }} Report (NPT)</p>
        <p style="margin: 4px 0 0 0; font-size: 13px; color: #475569;"><strong>Time Window:</strong> {{ $timeWindowText }}</p>
        <p style="margin: 6px 0 0 0; font-size: 14px;"><strong>Highest Risk Level:</strong> <strong style="color: {{ str_starts_with($highestRisk, 'RED') ? '#dc2626' : (str_starts_with($highestRisk, 'YELLOW') ? '#d97706' : '#16a34a') }}">{{ $highestRisk }}</strong></p>
        <p style="margin: 4px 0 0 0; font-size: 14px;"><strong>Verified Items Found:</strong> {{ $totalMentions }}</p>
    </div>

    @if($totalMentions > 0)
        <p style="font-size: 14px; color: #334155;">
            Attached is the official PDF report containing the executive assessment, risk tier breakdown, and itemized media findings for this monitoring slot.
        </p>
    @else
        <p style="font-size: 14px; color: #166534; background: #dcfce7; padding: 8px 12px; border-radius: 6px;">
            ✅ <strong>Operational Clearance:</strong> 0 actionable risk mentions or protest mobilizations were detected within this window. See attached summary for confirmation.
        </p>
    @endif

    <hr style="border: none; border-top: 1px solid #e2e8f0; margin: 20px 0;">
    <p style="font-size: 11px; color: #94a3b8;">
        This automated risk monitoring report is generated by Tamakoshi Monitor (UT-1 Risk Intelligence System) for NWEDC and Project Leadership.
    </p>
</body>
</html>